sudo: required

services:
  - docker

notifications:
  email: false
  webhooks:
    urls:
        - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGF6dWJpZXRhJTNBbWF0cml4Lm9yZy8lMjFGVUFDclFFZGZhSXpHT2xhSUolM0FtYXRyaXgub3Jn"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never

before_install:
  - docker pull nxos/nxos

script:
  - docker run --rm -v $(pwd)/:/build/ -w /build/ nxos/nxos bash build_scripts/travis-build.sh

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - if [ -z "$TRAVIS_TAG" ]; then
      export TRAVIS_TAG="continuous";
      git tag -f $TRAVIS_TAG;
    fi
  - mkdir out
  - mv -v Software_Center*.AppImage* out/
  - echo "========  UPLOADING TO TRANSFER.SH  ========"
  - curl --upload-file out/Software_Center*.AppImage https://transfer.sh/


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.email "none@nitrux.org"
  - git tag "continuous" -f

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: out/*
  skip_cleanup: true
  prerelease: true
  overwrite: true
  on:
    repo: nomad-desktop/nx-software-center
    all_branches: true
