language: cpp
compiler: gcc
sudo: require
dist: xenial

notifications:
  email: false
  webhooks:
    urls:
        - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGF6dWJpZXRhJTNBbWF0cml4Lm9yZy8lMjFGVUFDclFFZGZhSXpHT2xhSUolM0FtYXRyaXgub3Jn"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never

before_install:
  - wget -qO - http://archive.neon.kde.org/public.key | sudo apt-key add -
  - echo "deb http://archive.neon.kde.org/user/ xenial main" | sudo tee /etc/apt/sources.list.d/neon.list
  - wget -qO - http://repo.nxos.org/public.key | sudo apt-key add -
  - echo "deb http://repo.nxos.org nxos main" | sudo tee /etc/apt/sources.list.d/nxos.list
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install --allow-unauthenticated inkscape git cmake patchelf extra-cmake-modules qtdeclarative5-dev-tools
    qml-module-qtgraphicaleffects plasma-framework-dev qtbase5-dev qtdeclarative5-dev libqt5xmlpatterns5-dev nomad-plasma-look-and-feel
    luv-icon-theme nomad-desktop-settings

script:
  - cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - build_scripts/appimage.create.sh

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f
    2-3 | sort | uniq
  - if [ -z "$TRAVIS_TAG" ]; then
        export TRAVIS_TAG="continuous";
        git tag -f $TRAVIS_TAG;
      fi
  - mkdir out
  - mv -v Software_Center*.AppImage* out/
  - curl --upload-file out/Software_Center*.AppImage https://transfer.sh/nx_software_center

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: out/*
  skip_cleanup: true
  prerelease: true
  on:
    repo: nomad-desktop/nx-software-center
    tags: true
    all_branches: true
