language: cpp
compiler: gcc
sudo: require
dist: trusty

notifications:
  email: false
  webhooks:
    urls:
        - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGF6dWJpZXRhJTNBbWF0cml4Lm9yZy8lMjFGVUFDclFFZGZhSXpHT2xhSUolM0FtYXRyaXgub3Jn"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install --allow-unauthenticated cmake git qt59base qt59declarative
    inkscape
  - source /opt/qt*/bin/qt*-env.sh
  -
  - wget -c "https://github.com/chigraph/precompiled-kf5-linux/releases/download/precompiled/kf5-gcc6-linux64-release.tar.xz"
  - tar xf kf5-gcc6-linux64-release.tar.xz
  - sudo cp -Rf root/kf5-release/* /opt/qt*/
  - git clone git://anongit.kde.org/extra-cmake-modules
  - cd extra-cmake-modules
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
  - cd ../..
script:
  - cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR="appdir" -j$(nproc) install
  - find appdir/
  - # Create a png icon for the AppImage
  - wget -c -nv "https://raw.githubusercontent.com/nomad-desktop/luv-icon-theme/master/Luv/apps/64/nx-software-center.svg"
  - inkscape -z -e appdir/nx-software-center.png -w 256 -h 256 nx-software-center.svg
  - # Create the appimage
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD)
  - "./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop
    -qmldir=src/qml -bundle-non-qt-libs -appimage"
  - find appdir/
after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f
    2-3 | sort | uniq
  - if [ -z "$TRAVIS_TAG" ]; then
        export TRAVIS_TAG="continous";
      fi
  - mkdir out
  - mv -v Software_Center*.AppImage* out/

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: out/*
  on:
    repo: nomad-desktop/nx-software-center
    tags: true
    all_branches: true
